ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '1111';
FLUSH PRIVILEGES;

DROP DATABASE IF EXISTS phonebook;
CREATE DATABASE IF NOT EXISTS phonebook CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE phonebook;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(16) NOT NULL UNIQUE,
  email VARCHAR(190) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS contacts (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  phone VARCHAR(30) NOT NULL,
  email VARCHAR(190) NULL,
  image_path VARCHAR(255) NULL,
  CONSTRAINT fk_contacts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
